# mysql
mysql:
  username: root
  password: iTqGLjvu
  ipaddress: 172.16.32.27
  port: 52564
  dbname: douyin

# redis
redis:
  ipaddress: 172.16.32.27
  port: 52569
  authpassword: USBatlrS
  maxidle: 5              #连接池最大空闲数
  maxactive: 0            #连接池最大连接数 0 表示不设上

# resource(静态图片和视频的资源)
resouece:
  ipaddress: 192.168.31.30
  port: 3000